### ISSUE TITLE
missing tarballs for 2.1 version

### ISSUE THREAD

**Issue by ptrcnull** [folkertvanheusden/rsstail#1]
hey, i just noticed that the version 2.1 disappeared completely from the website - was it retracted, or what happened?

**Comment by folkertvanheusden** [comment]
Hi,

It is on GitHub only now.



Op vr 17 mrt. 2023 20:24 schreef Patrycja ***@***.***>:

**Comment by ptrcnull** [comment]
..there's no tags in the repo

![image](https://user-images.githubusercontent.com/26630168/228059249-3d1ec547-afed-485f-9236-f9851bfc173d.png)

**Comment by chenrui333** [comment]
@folkertvanheusden can you re-tag the 2.1 release? Thanks!

**Comment by catap** [comment]
> hey, i just noticed that the version 2.1 disappeared completely from the website - was it retracted, or what happened?

Wired things but github user had also changed :(

**Comment by folkertvanheusden** [comment]
yes
