### ISSUE TITLE
Potentially invalid public domain relicensing

### ISSUE THREAD

**Issue by emilazy** [folkertvanheusden/rsstail#7]
Hi there; I work on NixOS/Nixpkgs, a downstream distributor of `rsstail`. We try to keep up‐to‐date licence information for our packages, I noticed that in https://github.com/folkertvanheusden/rsstail/commit/106f6fe58a96cbbf0391ed72e46a9cb57137aeda the GPLv2 licence was replaced with a note declaring the code to be in the public domain. Putting aside jurisdictional issues with public domain, my concern is that you’ve merged contributions from several other people before that relicensing. The copyright in those contributions would be held by their original authors. Unless you’ve obtained consent from all those past contributors to release their changes into the public domain, to use their work under the GPLv2 licence they were contributed under, you’d have to retain the GPLv2 text, and `rsstail` as a whole would have to remain under that licence, even if you release your own work on it into the public domain. This is a legal problem for any distribution that wants to package and redistribute `rsstail` to users, so hopefully you can clarify the situation here – it might be best to simply restore the GPLv2 licence here to avoid copyright issues.

**Comment by folkertvanheusden** [comment]
I've put it back to GPLv2 now (in
commit a5ed53caa5d37947e0195b46c927b3fc7d50630d).

**Comment by emilazy** [comment]
Thanks for the extremely quick response to the annoying legal nit‐picking, and thanks for the software :)

Would you be able to restore the full licence text to the repository to comply with clause 1 of the GPLv2? It would be great for us as downstream distributors if you could make a new Git‐tagged release after that, too, as the already‐removed `libiconv_hook` was causing us issues.

**Comment by folkertvanheusden** [comment]
Hi,

Thanks.
I've added an v2.2 tag.

**Comment by emilazy** [comment]
Thank you! 💜 We’ll get an update shipped promptly.
